### ISSUE TITLE
Should previous guesses be used as base for future guesses?

### ISSUE THREAD

**Issue by clente** [Athospd/forkliftr#1]
I'm currently trying to implement the `guess_col_types` function.

I'd like to know whether I can use `guess_delim` inside `guess_col_types` so I'm able to reliably separate the columns. I'm using `readr::read_delim` to guess the column types, so having the delimiter would be necessary.

**Comment by Athospd** [comment]
In my opinion, YES.

I think that guess_delim() is covering about 99% of the most common situations right now.
One example of an edge situation that is covered already follows:

```
'0,0';'0,1'
'1,0';'1,1'
```

This case was solved by using a "a priori" rank for the delimiters where we assume subjective probabilities that sorts the characters from "the most common delimiter" to "not used as delimiter" (e.g.: from ";" to "A").

To check this "a priori" list just run `data("a_priori_delimiter_ranks", package = "forkliftr")`.
