### ISSUE TITLE
What should guess_delim output?

### ISSUE THREAD

**Issue by clente** [Athospd/forkliftr#4]
Currently `guess_delim` outputs a table with multiple probable delimiters and then the user selects the first one. Should the function return only the topmost delimiter?

**Comment by Athospd** [comment]
This is a good question. When we built guess_delim, I made the output to return a top 10 to be consistent with the output from readr::guess_encoding(). This function also returns a tibble ordered by relevance and with potentially more than one row.

But beside this, I have no other arguments left. 

One advantage that  I can bring to light right now is the possibility to frk_summarise_tabular_files() try again in case of failure.

what do you think?

**Comment by clente** [comment]
I agree with your second point! Thanks for the input.
